import React, { useState, useEffect, useRef } from 'react';
import { generateFlutterProject, ProjectFile, updateProjectFile } from '../services/gemini';
import { Icons } from './Icon';
import { GlassyLoader } from './GlassyLoader';
import JSZip from 'jszip';

export const FlutterBuilder: React.FC = () => {
  const [prompt, setPrompt] = useState('');
  const [status, setStatus] = useState<'idle' | 'generating' | 'ready'>('idle');
  const [files, setFiles] = useState<ProjectFile[]>([]);
  const [selectedFile, setSelectedFile] = useState<ProjectFile | null>(null);
  const [previewHTML, setPreviewHTML] = useState(''); // The visual simulation
  const [activeTab, setActiveTab] = useState<'editor' | 'preview'>('preview');
  const [logs, setLogs] = useState<string[]>([]);
  const [device, setDevice] = useState<'android' | 'ios'>('android');
  const [showSidebar, setShowSidebar] = useState(true);
  
  const [progress, setProgress] = useState(0);

  const addLog = (msg: string) => setLogs(prev => [...prev, `[${new Date().toLocaleTimeString()}] ${msg}`]);

  const handleContentChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
      if(!selectedFile) return;
      const newContent = e.target.value;
      const updatedFiles = files.map(f => f.path === selectedFile.path ? {...f, content: newContent} : f);
      setFiles(updatedFiles);
      setSelectedFile({...selectedFile, content: newContent});
  };

  const handleGenerate = async () => {
      if(!prompt.trim()) return;
      
      setStatus('generating');
      setLogs([]);
      setProgress(0);
      
      addLog("Initializing Flutter Engine...");
      addLog("Analyzing requirements for Material 3...");

      let p = 0;
      const interval = setInterval(() => {
          p += 5;
          if (p > 90) p = 90;
          setProgress(p);
      }, 500);

      try {
          const result = await generateFlutterProject(prompt, files);
          
          clearInterval(interval);
          setProgress(100);
          
          setFiles(result.files);
          setPreviewHTML(result.previewHTML);
          
          const mainFile = result.files.find(f => f.path.includes('main.dart')) || result.files[0];
          setSelectedFile(mainFile);
          
          setStatus('ready');
          addLog("Dart Code Generated.");
          addLog("Visual Simulator Ready.");

      } catch (e: any) {
          clearInterval(interval);
          setStatus('idle');
          addLog(`Error: ${e.message}`);
          alert("Generation failed. Please try again.");
      }
  };

  const downloadProject = async () => {
      const zip = new JSZip();
      files.forEach(f => {
          zip.file(f.path, f.content);
      });
      zip.file("README.md", "# Generated by Toma Ai Flutter Builder\n\n1. `flutter pub get`\n2. `flutter run`");
      
      const content = await zip.generateAsync({type:"blob"});
      const link = document.createElement('a');
      link.href = URL.createObjectURL(content);
      link.download = "flutter_project.zip";
      link.click();
  };

  return (
    <div className="flex flex-col h-full bg-[#09090b] text-slate-300 font-sans overflow-hidden">
        {/* Top Bar */}
        <div className="h-14 border-b border-white/10 flex items-center justify-between px-4 bg-black/40 backdrop-blur-md">
            <div className="flex items-center gap-3">
                <button 
                  onClick={() => setShowSidebar(!showSidebar)}
                  className={`p-1.5 rounded-lg border transition-all ${showSidebar ? 'bg-cyan-600/20 border-cyan-500/30 text-cyan-400' : 'bg-white/5 border-white/10 text-slate-400'}`}
                >
                    <Icons.Folder size={18} />
                </button>
                <div className="h-6 w-[1px] bg-white/10 mx-1"></div>
                <div className="p-1.5 bg-cyan-600/20 rounded-lg text-cyan-400 border border-cyan-500/30">
                    <Icons.Smartphone size={20} />
                </div>
                <div>
                    <h2 className="text-sm font-bold text-white tracking-wide">Flutter Builder <span className="text-[10px] px-1.5 py-0.5 rounded-full bg-blue-500/20 text-blue-300 border border-blue-500/30">BETA</span></h2>
                    <p className="text-[10px] text-slate-500">Dart • Material 3 • Multi-platform</p>
                </div>
            </div>

            <div className="flex gap-2">
                <button onClick={downloadProject} className="px-4 py-2 bg-blue-600/20 hover:bg-blue-600/30 text-blue-400 border border-blue-500/30 rounded-lg text-xs font-bold flex items-center gap-2 transition-all">
                    <Icons.Download size={14} /> Export Code
                </button>
            </div>
        </div>

        <div className="flex-1 flex overflow-hidden">
            {/* Sidebar: File Explorer */}
            <div className={`${showSidebar ? 'w-64 border-r border-white/5 opacity-100' : 'w-0 border-none opacity-0'} bg-black/20 flex flex-col transition-all duration-300 overflow-hidden`}>
                <div className="p-3 border-b border-white/5 flex items-center justify-between min-w-[16rem]">
                    <span className="text-xs font-bold uppercase tracking-widest text-slate-500">Project Files</span>
                </div>
                <div className="flex-1 overflow-y-auto custom-scrollbar p-2 min-w-[16rem]">
                    {files.length === 0 ? (
                        <div className="text-center mt-10 text-[10px] text-slate-600">
                            No files yet.
                        </div>
                    ) : (
                        <div className="flex flex-col gap-0.5">
                            {files.map((file) => (
                                <button
                                    key={file.path}
                                    onClick={() => { setSelectedFile(file); setActiveTab('editor'); }}
                                    className={`flex items-center gap-2 px-3 py-2 rounded-md text-xs text-left truncate transition-all ${selectedFile?.path === file.path ? 'bg-cyan-600/20 text-cyan-300' : 'hover:bg-white/5 text-slate-400'}`}
                                >
                                    {file.path.endsWith('.dart') ? <Icons.Code className="text-cyan-400" size={14}/> : 
                                     file.path.includes('yaml') ? <Icons.Settings className="text-yellow-400" size={14}/> :
                                     <Icons.File size={14} />}
                                    <span className="truncate">{file.path}</span>
                                </button>
                            ))}
                        </div>
                    )}
                </div>
            </div>

            {/* Main Area */}
            <div className="flex-1 flex flex-col min-w-0">
                {status === 'generating' ? (
                     <div className="flex-1 flex flex-col items-center justify-center relative">
                         <GlassyLoader text="Compiling Dart Modules..." size="lg" progress={progress} showSteps />
                         <div className="mt-4 h-32 w-2/3 bg-black/50 border border-white/10 rounded-xl p-4 overflow-y-auto custom-scrollbar font-mono text-[10px] text-cyan-400">
                             {logs.map((l, i) => <div key={i}>{l}</div>)}
                         </div>
                     </div>
                ) : files.length > 0 ? (
                    <>
                        <div className="h-10 bg-black/40 border-b border-white/5 flex items-center justify-between px-4">
                             <div className="flex gap-4 h-full">
                                 <button 
                                   onClick={() => setActiveTab('preview')}
                                   className={`h-full border-b-2 px-4 text-xs font-bold flex items-center gap-2 ${activeTab === 'preview' ? 'border-cyan-500 text-white' : 'border-transparent text-slate-500 hover:text-slate-300'}`}
                                 >
                                     <Icons.Play size={14} /> Emulator
                                 </button>
                                 <button 
                                   onClick={() => setActiveTab('editor')}
                                   className={`h-full border-b-2 px-4 text-xs font-bold flex items-center gap-2 ${activeTab === 'editor' ? 'border-blue-500 text-white' : 'border-transparent text-slate-500 hover:text-slate-300'}`}
                                 >
                                     <Icons.Code size={14} /> Dart Code
                                 </button>
                             </div>
                             
                             {activeTab === 'preview' && (
                                <div className="flex bg-white/5 rounded-lg p-0.5">
                                    <button onClick={() => setDevice('android')} className={`px-3 py-1 text-[10px] rounded transition-all ${device === 'android' ? 'bg-white/10 text-white' : 'text-slate-500'}`}>Android</button>
                                    <button onClick={() => setDevice('ios')} className={`px-3 py-1 text-[10px] rounded transition-all ${device === 'ios' ? 'bg-white/10 text-white' : 'text-slate-500'}`}>iOS</button>
                                </div>
                             )}
                        </div>

                        <div className="flex-1 bg-[#1e1e1e] overflow-hidden relative flex justify-center items-center p-4">
                             {activeTab === 'preview' ? (
                                 <div className={`relative bg-black border-4 border-slate-800 rounded-[3rem] shadow-2xl overflow-hidden transition-all duration-500 ${device === 'android' ? 'w-[360px] h-[740px]' : 'w-[375px] h-[812px]'}`}>
                                    {/* Notch/Camera */}
                                    <div className="absolute top-0 left-1/2 transform -translate-x-1/2 w-32 h-6 bg-black rounded-b-xl z-20"></div>
                                    
                                    {/* App Content (Simulated via HTML) */}
                                    <iframe 
                                        srcDoc={previewHTML}
                                        className="w-full h-full bg-white"
                                        title="Flutter Simulation"
                                    />
                                    
                                    {/* Home Bar */}
                                    <div className="absolute bottom-2 left-1/2 transform -translate-x-1/2 w-32 h-1 bg-white/20 rounded-full z-20"></div>
                                 </div>
                             ) : (
                                 <div className="w-full h-full relative">
                                    <textarea
                                        className="w-full h-full bg-[#1e1e1e] text-[#d4d4d4] font-mono text-sm p-4 outline-none resize-none leading-relaxed"
                                        spellCheck={false}
                                        value={selectedFile?.content || ''}
                                        onChange={handleContentChange}
                                        placeholder="// Select a file to edit code..."
                                    />
                                 </div>
                             )}
                        </div>
                    </>
                ) : (
                    <div className="flex-1 flex flex-col items-center justify-center text-center p-8">
                         <div className="w-24 h-24 bg-gradient-to-br from-cyan-600/20 to-blue-600/20 rounded-3xl flex items-center justify-center mb-6 border border-cyan-500/20">
                             <Icons.Smartphone size={48} className="text-cyan-400" />
                         </div>
                         <h3 className="text-2xl font-bold text-white mb-2">Flutter App Builder</h3>
                         <p className="text-slate-400 max-w-md text-sm mb-8">
                             Generate multi-file Flutter applications with code and a visual emulator simulation.
                         </p>
                    </div>
                )}

                {/* Prompt Area */}
                <div className="h-auto min-h-[80px] border-t border-white/10 bg-black/60 backdrop-blur p-4">
                    <div className="max-w-4xl mx-auto flex gap-3">
                         <div className="flex-1 relative">
                             <input 
                               type="text" 
                               value={prompt}
                               onChange={(e) => setPrompt(e.target.value)}
                               onKeyDown={(e) => e.key === 'Enter' && handleGenerate()}
                               placeholder="Describe your App (e.g. Chat App with Dark Mode, E-commerce login)..."
                               className="w-full h-12 bg-white/5 border border-white/10 rounded-xl px-4 text-sm text-white focus:ring-1 focus:ring-cyan-500/50 outline-none"
                             />
                         </div>
                         <button 
                            onClick={handleGenerate}
                            className="px-6 h-12 rounded-xl font-bold text-white shadow-lg transition-all flex items-center gap-2 bg-cyan-600 hover:bg-cyan-500"
                         >
                             {status === 'generating' ? <Icons.Loader className="animate-spin" /> : <Icons.Send />}
                         </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
  );
};